# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06d44b47bbbde53692f3f86882ca0b0c73a3b173336999ba253c95b2983c88aa21c1fd2170d5c6904768dc93a9cc7cf102b258052d9bae3262f232469a4ad5bc

test:
  secret_key_base: 4724da2167349f954dea14efe7f0dbd7d80d98aa582f71bc23dd8dda52c54c3c244c014edaf830d136a427d28d333570bfa47e093609c2a5090d0c0e33d40670

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
